apiVersion: apps/v1
kind: Deployment
metadata:
  name: kauppalista-api
  labels:
    app: kauppalista-api
  namespace: kauppalista
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kauppalista-api
  template:
    metadata:
      labels:
        app: kauppalista-api
    spec:
      containers:
        - name: kauppalista-api
          image: registry.kelhala.com/kauppalista-api:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
          env:
            - name: PSQL_HOST
              value: "kauppalistadb-service.kauppalista.svc.cluster.local"
            - name: PSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: PSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: PSQL_DB
              value: "kauppalista"
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret
                  key: client-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "600m"
            limits:
              memory: "1024Mi"
              cpu: "1200m"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 6
      volumes:
        - name: config-volume
          configMap:
            name: api-config
            items:
              - key: config.yaml
                path: config.yaml
      imagePullSecrets:
        - name: registry-cred