apiVersion: v1
kind: Service
metadata:
  name: kauppalista-api-svc
  labels:
    app: kauppalista-api
  namespace: kauppalista
spec:
  selector:
    app: kauppalista-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP