cors:
  allowOrigins:
    - "http://localhost:5173"
  allowCredentials: true
server:
  port: 9000
  host: 127.0.0.1
redis:
  host: localhost
  port: 6379
keycloak:
  issuer: "https://keycloak.kelhala.com/realms/kauppalista"
  client_id: "account"