cors:
  allowOrigins:
    - "http://localhost:3000"
  allowCredentials: true
server:
  port: 9000
  host: 0.0.0.0
redis:
  host: localhost
  port: 6379
auth0:
  issuer: "https://your-tenant.auth0.com/"
  api_audience: "kauppalista-api"
  management_audience: "https://your-tenant.auth0.com/api/v2/"
  management_client_id: "your-management-client-id"